[phases.setup]
# GANTI HASH INI DENGAN YANG LEBIH LAMA DAN PASTI MASIH PUNYA PHP 7.4
legacyNixPkgs = "https://github.com/NixOS/nixpkgs/archive/f2c41864114f434033f114a904037563065a7f92.tar.gz" # <-- GANTI INI!

packages = [
  "php74",
  "php74Extensions.composer",
  "php74Extensions.pdo_pgsql",
  "php74Extensions.gd",
  "php74Extensions.mbstring",
  "php74Extensions.openssl",
  "php74Extensions.curl",
  "php74Extensions.json",
  "php74Extensions.zip"
  # Tambahkan ekstensi PHP 7.4 lain di sini jika ada error build yang mengeluhkannya
]

apt = ["git", "libpq-dev"]

[phases.build]
commands = ["npm install"]

[phases.postBuild]
commands = ["npm run prod"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"

# Konfigurasi jika aplikasi kamu adalah SPA atau menggunakan history mode
# [web.static_root]
# root = "public"
# headers = { "Cache-Control" = "no-cache, no-store, must-revalidate" }